# Generated by Django 2.2 on 2019-06-22 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelTelesa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kraj',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mesto', models.CharField(default='', max_length=100)),
                ('postnaStevilka', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Naprava',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('ime', models.CharField(max_length=100)),
                ('priimek', models.CharField(max_length=100)),
                ('spol', models.CharField(choices=[('M', 'Moški'), ('Ž', 'Ženska')], default='M', max_length=1)),
                ('rojstniDatum', models.DateField()),
                ('emso', models.PositiveIntegerField()),
                ('ulica', models.CharField(default='', max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HIS.Kraj')),
            ],
        ),
        migrations.CreateModel(
            name='Slikanje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delTelesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HIS.DelTelesa')),
                ('naprava', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HIS.Naprava')),
            ],
        ),
        migrations.CreateModel(
            name='Pregled',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregledDatum', models.DateField()),
                ('pacient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HIS.Pacient')),
                ('tipSlikanja', models.ManyToManyField(blank=True, null=True, to='HIS.Slikanje')),
            ],
        ),
    ]
