# Generated by Django 2.2 on 2019-06-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kraj',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='kraj',
            unique_together={('mesto', 'postnaStevilka')},
        ),
    ]
