# Generated by Django 2.2 on 2019-06-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0002_auto_20190624_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kraj',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='kraj',
            unique_together=set(),
        ),
    ]
