# Generated by Django 2.2 on 2019-06-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0003_auto_20190624_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='naprava',
            name='kratica',
            field=models.CharField(default='', max_length=25),
        ),
    ]
