# Generated by Django 2.2 on 2019-07-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0004_naprava_kratica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slikanje',
            name='delTelesa',
        ),
        migrations.RemoveField(
            model_name='slikanje',
            name='naprava',
        ),
        migrations.AddField(
            model_name='slikanje',
            name='SPS_koda',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slikanje',
            name='koda',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='slikanje',
            name='opis',
            field=models.CharField(default='', max_length=500),
        ),
    ]
