# Generated by Django 2.2 on 2019-07-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0005_auto_20190723_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slikanje',
            name='koda',
            field=models.CharField(default='', max_length=10),
        ),
    ]
