# Generated by Django 2.2 on 2019-07-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0006_auto_20190723_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregled',
            name='pregledDatum',
            field=models.DateField(auto_now=True),
        ),
    ]
