# Generated by Django 2.2 on 2019-07-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0008_auto_20190723_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slikanje',
            name='SPS_koda',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
